### ISSUE TITLE
Make values for different size configurable

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-charts#20]
### Summary

The values are on hardcoded in the config:

```yaml
memory:
        small: 64
        medium: 128
        large: 256
      cpu:
        small: 0.1
        medium: 0.25
        large: 0.5
```
That needs to be configurable via chart.
